development:
  adapter: postgresql
  encoding: unicode
  database: nvoice_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: nvoice_test
  pool: 5
  username: postgres
  password: postgres